name: Test and build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Lint and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: cp install/package.json package.json

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: NPM Install
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Build Nodebb
        run: ./nodebb build